using System.Collections.Generic;
using halisahaapp.webui.Models;

namespace halisahaapp.webui.Helper
{
    public static class CityHelper
    {


        public static List<City> cities = new List<City> {
            new City(){Name = "Adana", PlakaNo="01"},
            new City(){Name = "Adıyaman", PlakaNo="02"},
            new City(){Name = "Afyon karahi̇sar", PlakaNo="03"},
            new City(){Name = "Ağrı", PlakaNo="04"},
            new City(){Name = "Amasya", PlakaNo="05"},
            new City(){Name = "Ankara", PlakaNo="06"},
            new City(){Name = "Antalya", PlakaNo="07"},
            new City(){Name = "Artvi̇n", PlakaNo="08"},
            new City(){Name = "Aydın", PlakaNo="09"},
            new City(){Name = "Balıkesi̇r", PlakaNo="10"},
            new City(){Name = "Bi̇leci̇k", PlakaNo="11"},
            new City(){Name = "Bi̇ngöl", PlakaNo="12"},
            new City(){Name = "Bi̇tli̇s", PlakaNo="13"},
            new City(){Name = "Bolu", PlakaNo="14"},
            new City(){Name = "Burdur", PlakaNo="15"},
            new City(){Name = "Bursa", PlakaNo="16"},
            new City(){Name = "Çanakkale", PlakaNo="17"},
            new City(){Name = "Çankırı", PlakaNo="18"},
            new City(){Name = "Çorum", PlakaNo="19"},
            new City(){Name = "Deni̇zli̇", PlakaNo="20"},
            new City(){Name = "Di̇yarbakır", PlakaNo="21"},
            new City(){Name = "Edi̇rne", PlakaNo="22"},
            new City(){Name = "Elazığ", PlakaNo="23"},
            new City(){Name = "Erzi̇ncan", PlakaNo="24"},
            new City(){Name = "Erzurum", PlakaNo="25"},
            new City(){Name = "Eski̇şehi̇r", PlakaNo="26"},
            new City(){Name = "Gazi̇antep", PlakaNo="27"},
            new City(){Name = "Gi̇resun", PlakaNo="28"},
            new City(){Name = "Gümüşhane", PlakaNo="29"},
            new City(){Name = "Hakkari̇", PlakaNo="30"},
            new City(){Name = "Hatay", PlakaNo="31"},
            new City(){Name = "Isparta", PlakaNo="32"},
            new City(){Name = "Mersi̇n", PlakaNo="33"},
            new City(){Name = "stanbul", PlakaNo="34"},
            new City(){Name = "İzmi̇r", PlakaNo="35"},
            new City(){Name = "Kars", PlakaNo="36"},
            new City(){Name = "Kastamonu", PlakaNo="37"},
            new City(){Name = "Kayseri̇", PlakaNo="38"},
            new City(){Name = "Kırklareli̇", PlakaNo="39"},
            new City(){Name = "Kırşehi̇r", PlakaNo="40"},
            new City(){Name = "Kocaeli̇", PlakaNo="41"},
            new City(){Name = "Konya", PlakaNo="42"},
            new City(){Name = "Kütahya", PlakaNo="43"},
            new City(){Name = "Malatya", PlakaNo="44"},
            new City(){Name = "Mani̇sa", PlakaNo="45"},
            new City(){Name = "Kahraman maraş", PlakaNo="46"},
            new City(){Name = "Mardi̇n", PlakaNo="47"},
            new City(){Name = "Muğla", PlakaNo="48"},
            new City(){Name = "Muş", PlakaNo="49"},
            new City(){Name = "Nevşehi̇r", PlakaNo="50"},
            new City(){Name = "Ni̇ğde", PlakaNo="51"},
            new City(){Name = "Ordu", PlakaNo="52"},
            new City(){Name = "Ri̇ze", PlakaNo="53"},
            new City(){Name = "Sakarya", PlakaNo="54"},
            new City(){Name = "Samsun", PlakaNo="55"},
            new City(){Name = "Si̇i̇rt", PlakaNo="56"},
            new City(){Name = "Si̇nop", PlakaNo="57"},
            new City(){Name = "Si̇vas", PlakaNo="58"},
            new City(){Name = "Teki̇rdağ", PlakaNo="59"},
            new City(){Name = "Tokat", PlakaNo="60"},
            new City(){Name = "Trabzon", PlakaNo="61"},
            new City(){Name = "Tunceli̇", PlakaNo="62"},
            new City(){Name = "Şanlıurfa", PlakaNo="63"},
            new City(){Name = "Uşak", PlakaNo="64"},
            new City(){Name = "Van", PlakaNo="65"},
            new City(){Name = "Yozgat", PlakaNo="66"},
            new City(){Name = "Zonguldak", PlakaNo="67"},
            new City(){Name = "Aksaray", PlakaNo="68"},
            new City(){Name = "Bayburt", PlakaNo="69"},
            new City(){Name = "Karaman", PlakaNo="70"},
            new City(){Name = "Kırıkkale", PlakaNo="71"},
            new City(){Name = "Batman", PlakaNo="72"},
            new City(){Name = "Şırnak", PlakaNo="73"},
            new City(){Name = "Bartın", PlakaNo="74"},
            new City(){Name = "Ardahan", PlakaNo="75"},
            new City(){Name = "Iğdır", PlakaNo="76"},
            new City(){Name = "Yalova", PlakaNo="77"},
            new City(){Name = "Karabük", PlakaNo="78"},
            new City(){Name = "Ki̇li̇s", PlakaNo="79"},
            new City(){Name = "Osmani̇ye", PlakaNo="80"},
            new City(){Name = "Düzce", PlakaNo="81"},
        };
    }
}